server.port=8080
spring.application.name=url-shortener
server.servlet.context-path=/url-shortener
app.base-url=http://localhost:8080/url-shortener

# Logging Configuration
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{logRefId}] %-5level %logger{36} - %msg%n
logging.level.root=INFO
logging.level.com.example.urlshortener=DEBUG